/* Automatically @generated by tree-sitter v0.25.6 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 22
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 19
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_rule_definition_token1 = 1,
  aux_sym_class_definition_token1 = 2,
  anon_sym_self = 3,
  anon_sym_if = 4,
  anon_sym_else = 5,
  anon_sym_canvas = 6,
  aux_sym_dynamic_rule_token1 = 7,
  aux_sym_dynamic_rule_token2 = 8,
  sym_int_literal = 9,
  sym_source_file = 10,
  sym__definition = 11,
  sym_rule_definition = 12,
  sym_class_definition = 13,
  sym_property_definition = 14,
  sym_pair_definition = 15,
  sym_keyword_definition = 16,
  sym_dynamic_rule = 17,
  aux_sym_source_file_repeat1 = 18,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_rule_definition_token1] = "rule_definition_token1",
  [aux_sym_class_definition_token1] = "class_definition_token1",
  [anon_sym_self] = "self",
  [anon_sym_if] = "if",
  [anon_sym_else] = "else",
  [anon_sym_canvas] = "canvas",
  [aux_sym_dynamic_rule_token1] = "dynamic_rule_token1",
  [aux_sym_dynamic_rule_token2] = "dynamic_rule_token2",
  [sym_int_literal] = "int_literal",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_rule_definition] = "rule_definition",
  [sym_class_definition] = "class_definition",
  [sym_property_definition] = "property_definition",
  [sym_pair_definition] = "pair_definition",
  [sym_keyword_definition] = "keyword_definition",
  [sym_dynamic_rule] = "dynamic_rule",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_rule_definition_token1] = aux_sym_rule_definition_token1,
  [aux_sym_class_definition_token1] = aux_sym_class_definition_token1,
  [anon_sym_self] = anon_sym_self,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_canvas] = anon_sym_canvas,
  [aux_sym_dynamic_rule_token1] = aux_sym_dynamic_rule_token1,
  [aux_sym_dynamic_rule_token2] = aux_sym_dynamic_rule_token2,
  [sym_int_literal] = sym_int_literal,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_rule_definition] = sym_rule_definition,
  [sym_class_definition] = sym_class_definition,
  [sym_property_definition] = sym_property_definition,
  [sym_pair_definition] = sym_pair_definition,
  [sym_keyword_definition] = sym_keyword_definition,
  [sym_dynamic_rule] = sym_dynamic_rule,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_rule_definition_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_class_definition_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_self] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_canvas] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_dynamic_rule_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dynamic_rule_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_int_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_rule_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_class_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_property_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_pair_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_keyword_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_dynamic_rule] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(35);
      if (lookahead == '<') ADVANCE(11);
      if (lookahead == 'c') ADVANCE(18);
      if (lookahead == 'e') ADVANCE(24);
      if (lookahead == 'i') ADVANCE(22);
      if (lookahead == 's') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 1:
      if (lookahead == '+') ADVANCE(14);
      if (lookahead == '>') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '+') ADVANCE(14);
      if (lookahead == '>') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '+') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(2);
      END_STATE();
    case 4:
      if (lookahead == ':') ADVANCE(36);
      END_STATE();
    case 5:
      if (lookahead == ':') ADVANCE(42);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(43);
      END_STATE();
    case 7:
      if (lookahead == ':') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '<') ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(7);
      END_STATE();
    case 9:
      if (lookahead == '>') ADVANCE(4);
      if (lookahead == '@') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '>') ADVANCE(4);
      if (lookahead == '@') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == '>') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(9);
      END_STATE();
    case 12:
      if (lookahead == '>') ADVANCE(4);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == '>') ADVANCE(5);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      if (lookahead == '>') ADVANCE(6);
      if (lookahead == '+' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(14);
      END_STATE();
    case 15:
      if (lookahead == '@') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      if (lookahead == '@') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      if (lookahead == '@') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'a') ADVANCE(27);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 22:
      if (lookahead == 'f') ADVANCE(39);
      END_STATE();
    case 23:
      if (lookahead == 'f') ADVANCE(38);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(28);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(29);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(41);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(20);
      END_STATE();
    case 29:
      if (lookahead == 'v') ADVANCE(19);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(1);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(17);
      END_STATE();
    case 34:
      if (eof) ADVANCE(35);
      if (lookahead == '<') ADVANCE(12);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(34);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_rule_definition_token1);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_class_definition_token1);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_self);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_canvas);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_dynamic_rule_token1);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_dynamic_rule_token2);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_int_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(44);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 34},
  [2] = {.lex_state = 34},
  [3] = {.lex_state = 34},
  [4] = {.lex_state = 34},
  [5] = {.lex_state = 34},
  [6] = {.lex_state = 34},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_rule_definition_token1] = ACTIONS(1),
    [anon_sym_self] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_canvas] = ACTIONS(1),
    [aux_sym_dynamic_rule_token1] = ACTIONS(1),
    [aux_sym_dynamic_rule_token2] = ACTIONS(1),
    [sym_int_literal] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(14),
    [sym__definition] = STATE(2),
    [sym_rule_definition] = STATE(2),
    [sym_dynamic_rule] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_rule_definition_token1] = ACTIONS(5),
    [aux_sym_dynamic_rule_token1] = ACTIONS(7),
    [sym_int_literal] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      aux_sym_rule_definition_token1,
    ACTIONS(7), 1,
      aux_sym_dynamic_rule_token1,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      sym_int_literal,
    STATE(3), 4,
      sym__definition,
      sym_rule_definition,
      sym_dynamic_rule,
      aux_sym_source_file_repeat1,
  [19] = 5,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      aux_sym_rule_definition_token1,
    ACTIONS(20), 1,
      aux_sym_dynamic_rule_token1,
    ACTIONS(23), 1,
      sym_int_literal,
    STATE(3), 4,
      sym__definition,
      sym_rule_definition,
      sym_dynamic_rule,
      aux_sym_source_file_repeat1,
  [38] = 1,
    ACTIONS(26), 4,
      ts_builtin_sym_end,
      aux_sym_rule_definition_token1,
      aux_sym_dynamic_rule_token1,
      sym_int_literal,
  [45] = 1,
    ACTIONS(28), 4,
      ts_builtin_sym_end,
      aux_sym_rule_definition_token1,
      aux_sym_dynamic_rule_token1,
      sym_int_literal,
  [52] = 1,
    ACTIONS(30), 4,
      ts_builtin_sym_end,
      aux_sym_rule_definition_token1,
      aux_sym_dynamic_rule_token1,
      sym_int_literal,
  [59] = 2,
    ACTIONS(32), 1,
      aux_sym_class_definition_token1,
    STATE(15), 1,
      sym_property_definition,
  [66] = 2,
    ACTIONS(34), 1,
      aux_sym_class_definition_token1,
    STATE(12), 1,
      sym_class_definition,
  [73] = 2,
    ACTIONS(34), 1,
      aux_sym_class_definition_token1,
    STATE(10), 1,
      sym_class_definition,
  [80] = 2,
    ACTIONS(36), 1,
      anon_sym_self,
    STATE(4), 1,
      sym_keyword_definition,
  [87] = 2,
    ACTIONS(38), 1,
      aux_sym_class_definition_token1,
    STATE(17), 1,
      sym_pair_definition,
  [94] = 2,
    ACTIONS(36), 1,
      anon_sym_self,
    STATE(5), 1,
      sym_keyword_definition,
  [101] = 1,
    ACTIONS(40), 1,
      aux_sym_dynamic_rule_token2,
  [105] = 1,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
  [109] = 1,
    ACTIONS(44), 1,
      anon_sym_self,
  [113] = 1,
    ACTIONS(46), 1,
      aux_sym_class_definition_token1,
  [117] = 1,
    ACTIONS(48), 1,
      anon_sym_self,
  [121] = 1,
    ACTIONS(50), 1,
      anon_sym_else,
  [125] = 1,
    ACTIONS(52), 1,
      anon_sym_if,
  [129] = 1,
    ACTIONS(54), 1,
      anon_sym_self,
  [133] = 1,
    ACTIONS(56), 1,
      anon_sym_canvas,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 19,
  [SMALL_STATE(4)] = 38,
  [SMALL_STATE(5)] = 45,
  [SMALL_STATE(6)] = 52,
  [SMALL_STATE(7)] = 59,
  [SMALL_STATE(8)] = 66,
  [SMALL_STATE(9)] = 73,
  [SMALL_STATE(10)] = 80,
  [SMALL_STATE(11)] = 87,
  [SMALL_STATE(12)] = 94,
  [SMALL_STATE(13)] = 101,
  [SMALL_STATE(14)] = 105,
  [SMALL_STATE(15)] = 109,
  [SMALL_STATE(16)] = 113,
  [SMALL_STATE(17)] = 117,
  [SMALL_STATE(18)] = 121,
  [SMALL_STATE(19)] = 125,
  [SMALL_STATE(20)] = 129,
  [SMALL_STATE(21)] = 133,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_rule_definition, 3, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dynamic_rule, 4, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_keyword_definition, 4, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [42] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_class_definition, 2, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_definition, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pair_definition, 2, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_kvlang(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "kvlang",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
